;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-or-indentation
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        delete-horizontal-space
        delete-indentation
        electric-newline-and-maybe-indent
        eval-and-replace
        eval-last-sexp
        eval-print-last-sexp
        forward-sexp
        isearch-abort
        isearch-forward-regexp
        isearch-printing-char
        isearch-repeat-forward
        ivy-switch-buffer
        keyboard-quit
        kill-region
        kmacro-start-macro-or-insert-counter
        nxml-electric-slash
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        sgml-slash
        subword-right
        tab-to-tab-stop
        top-join-line
        web-mode-navigate
        zop-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        god-local-mode
        god-mode-self-insert
        helm-M-x
        helm-mini
        helm-projectile
        hsplit-last-buffer
        ido-switch-buffer
        isearch-delete-char
        mark-whole-buffer
        mouse-secondary-save-then-kill
        mouse-set-region
        mouse-set-secondary
        projectile-switch-to-buffer
        repeat
        smex
        swiper
        undo-tree-visualize
        yas-expand
        ))
