;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-or-indentation
        c-electric-semi&comma
        isearch-abort
        isearch-forward-regexp
        isearch-printing-char
        isearch-repeat-forward
        kill-region
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-delete-char
        repeat
        smex
        ))
