(defun my-update-cursor ()
  (let ((limited-colors-p (> 257 (length (defined-colors)))))
    (cond (god-local-mode (progn
                            (set-face-background 'mode-line (if limited-colors-p "red" "#cb202d"))
                            (set-face-background 'mode-line-inactive (if limited-colors-p "red" "#cb202d"))
                            (setq cursor-type 'hbar )))
          (t (progn
               (set-face-background 'mode-line (if limited-colors-p "black" "#0a2832"))
               (set-face-background 'mode-line-inactive (if limited-colors-p "black" "#0a2832"))
               (setq cursor-type 'box ))))))
(add-hook 'god-mode-enabled-hook 'my-update-cursor)
(add-hook 'god-mode-disabled-hook 'my-update-cursor)
(god-local-mode t)
(define-key god-local-mode-map (kbd ".") 'repeat)
(define-key god-local-mode-map (kbd "z") 'keyboard-quit)
(define-key god-local-mode-map (kbd "i") 'god-local-mode)
(god-local-mode -1)
